### ISSUE TITLE
ModuleNotFoundError: No module named 'cython_bbox'

### ISSUE THREAD

**Issue by YumnaBatool** [ifzhang/FairMOT#25]
I followed all the instructions for installation and then tried this command,

python3 demo.py mot --load_model ../models/all_dla34.pth --conf_thres 0.4

I have done cython_bbox installation using pip3 in the conda environment. But still receiving this error.

**Comment by egorsmkv** [comment]
You need to install cython also.

**Comment by zzfpython** [comment]
> You need to install cython also.

I encounted this problem also. However affer I try pip install cython "You have already installed this". Can you tell me how to handle this problem

**Comment by YumnaBatool** [comment]
@egorsmkv I installed cython using "conda install cython". Still I am facing this issue. Please suggest how to resolve it.

**Comment by ylc2580** [comment]
> > You need to install cython also.
> 
> I encounted this problem also. However affer I try pip install cython "You have already installed this". Can you tell me how to handle this problem

maybe you should attention your python version

**Comment by egorsmkv** [comment]
After installing cython using pip you need to install packages from the requirements.txt

**Comment by KevenLee** [comment]
> cython_bbox is widely used in object detection tasks. To my best knowledge, it was first implemented in [Faster-RCNN](https://github.com/rbgirshick/py-faster-rcnn). Since then, almost all object detection projects use the source code directly.
> 
> In order to use it in standalone code snippets or small projects, I make it a pypi module. The `cython_bbox.pyx` is totally borrowed from [Faster-RCNN](https://github.com/rbgirshick/py-faster-rcnn). Thanks [RBG](http://www.rossgirshick.info/)!

> ## install
> 
> ```
> pip install cython_bbox
> ```
> 
> ## usage
> 
> 
> ```
> from cython_bbox import bbox_overlaps
> overlaps = bbox_overlaps(
> np.ascontiguousarray(dt, dtype=np.float32),
> np.ascontiguousarray(gt, dtype=np.float32)
> )

[https://pypi.org/project/cython-bbox/](url)

so, you should just install cython_bbox

**Comment by YumnaBatool** [comment]
I solved the issue by installing cython_bbox using pip not pip3.

I figured out that the conda environment is using pip instead of pip3. I used "which pip" and "which python" in conda environment to find out the versions conda environment is using.

Than installed cython_bbox by "pip install cython_bbox"

**Comment by YumnaBatool** [comment]
I am closing the issue as it is solved.

**Comment by MrAsimZahid** [comment]
For Windows solution

https://stackoverflow.com/questions/60349980/is-there-a-way-to-install-cython-bbox-for-windows

**Comment by LOGIC-10** [comment]
it doesn't help. problem still unresolved . I'm in Ubuntu 16.04.I have installed cython_bbox and cython both in condo and pip ...
how can I solve this problem
